src/objects/AppActivity__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>App Activity</relationshipLabel>
        <relationshipName>App_Activity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>App Activity</relationshipLabel>
        <relationshipName>App_Activity1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>App_Activity1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>App Activity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Activity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Broker__c.object
<CustomObject>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateAppActivityREST.cls
@RestResource(urlMapping='/CreateAppActivity/*')
global with sharing class CreateAppActivityREST {

@HttpGet
  global static void create() {
      RestContext.response.addHeader('Content-Type', 'application/json');
    try {
        ID property = RestContext.request.params.get('property');
        ID broker = RestContext.request.params.get('broker');
        string message = RestContext.request.params.get('message');
        ID user = UserInfo.getUserId();
        AppActivity__c appactivity = new AppActivity__c();
        appactivity.Name = message;
        appactivity.Property__c = property;
        appactivity.Broker__c = broker;
        appactivity.User__c = user;
        insert appactivity;
        RestContext.response.responseBody = Blob.valueOf('{ "message" : "Success" }');
    } catch (Exception e) {
        RestContext.response.responseBody = Blob.valueOf('{ "message" : "Error" }');
    }
}
}