src/objects/Favorite__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Favorites</relationshipLabel>
        <relationshipName>Favorites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Favorites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorite</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Favorite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PushPropertyRecommendation.cls
public with sharing class PushPropertyRecommendation {

	@InvocableMethod(label='Push Property Recommendation' description='Send a customer notification when brokers recommend a property.')
	public static void pushNotification (List<string> favoriteIDs) {
        Id favoriteID = favoriteIDs[0]; // If bulk, only post first to avoid spamming
        Favorite__c favorite = [SELECT Property__c, Recommendation__c, User__c, CreatedById from Favorite__c WHERE Id=:favoriteId];
        Property__c property = [SELECT Name, Price__c from Property__c WHERE Id=:favorite.Property__c];
        User broker = [SELECT Name FROM User WHERE Id=:favorite.CreatedById];
        //String message = '{aps: {alert: "' + broker.Name + ' suggested you look at this property: ' + property.Name + ' - $' + property.Price__c.setScale(0).format() + '",sound: "default"}}';
        //String message = '{alert: "' + broker.Name + ' suggested you look at this property: ' + property.Name + ' - $' + property.Price__c.setScale(0).format() + '",sound: "default"}';
        String message = 'Your broker suggested you look at this property: ' + property.Name + ' - $' + property.Price__c.setScale(0).format();

        Set<String> userIds = new Set<String>();
        userIds.add(favorite.user__c);

        Messaging.PushNotification msg =  new Messaging.PushNotification();
        Map<String, Object> payload = Messaging.PushNotificationPayload.apple(message, '', null, null);
        msg.setPayload(payload);
        msg.send('DreamHouse_Mobile_App', userIds);
    }
}