src/objects/Favorite__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Favorites</relationshipLabel>
        <relationshipName>Favorites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Favorites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorite</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Favorite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateFavoriteREST.cls
@RestResource(urlMapping='/CreateFavorite/*')
global with sharing class CreateFavoriteREST {

@HttpGet
  global static void create() {
      RestContext.response.addHeader('Content-Type', 'application/json');
    try {
        ID propertyID = RestContext.request.params.get('id');
        ID userID = UserInfo.getUserId();
        Favorite__c favorite = new Favorite__c();
        favorite.Property__c = propertyID;
        favorite.User__c = userID;
        insert favorite;
        RestContext.response.responseBody = Blob.valueOf('{ "message" : "Success" }');
    } catch (Exception e) {
        RestContext.response.responseBody = Blob.valueOf('{ "message" : "Error" }');
    }
}
}